<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ page
	import="java.util.*, cems.staffBean, java.text.SimpleDateFormat"%>
<%
// Retrieve data from Controller
Map<String, Object> reportData = (Map<String, Object>) request.getAttribute("reportData");

if (reportData == null) {
	out.println("<div class='report-card'><h3 style='color:red;'>Error: No report data found. Please generate the report via the Dashboard.</h3></div>");
	return; 
}

String startDate = (String) request.getAttribute("startDate");
String endDate = (String) request.getAttribute("endDate");
String reportType = (String) request.getAttribute("reportType");

staffBean staff = (staffBean) session.getAttribute("staff");
SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
String today = sdf.format(new Date());
%>

<!DOCTYPE html>
<html>
<head>
<title><%=reportType%> Report</title>
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="styleReport.css">
</head>
<body>
<main>
	<div class="report-card">
	<div class="detail-header-stack">
					<button class="back-link"
						onclick="window.location.href='generateReport.jsp'">
						<i class="fas fa-arrow-left"></i> Back
					</button>
				</div>
        <div class="header-grid">
            <div>
                <h1 class="report-title"><%=reportType%> Report - <%=today.substring(3)%></h1>
                <div class="meta-info">
                    <p><strong>Date Range:</strong> <%=startDate%> until <%=endDate%></p>
                </div>
            </div>
            <div class="meta-info" style="text-align: right;">
                <p><strong>Generated by:</strong> <%=(staff != null) ? staff.getStaffName() : "Manager"%></p>
                <p><strong>Date Generated:</strong> <%=today%></p>
            </div>
        </div>

        <div class="stats-box">
			<h2>Summary Statistics</h2>
			<% if ("Event".equals(reportType)) { %>
                <p><strong>Total Events Conducted:</strong> <%=reportData.get("totalItems")%></p>
                <p><strong>Total Guests Served:</strong> <%=reportData.get("totalGuests")%></p>
			<% } else { %>
                <p><strong>Total Assigned:</strong> <%=reportData.get("totalAssigned")%></p>
                <p><strong>Total Returned:</strong> <%=reportData.get("totalReturned")%></p>
                <p><strong>Total Damaged:</strong> <span class="qty-danger"><%=reportData.get("totalDamaged")%></span></p>
                <p><strong>Total Lost:</strong> <span class="qty-warning"><%=reportData.get("totalLost")%></span></p>
			<% } %>
		</div>

		<h3 class="table-title">
            <%="Event".equals(reportType) ? "List of events conducted:" : "List of equipment damaged/lost:" %>
        </h3>
        
		<table class="table">
    <thead>
        <tr>
            <% if ("Event".equals(reportType)) { %>
                <th>Event ID</th>
                <th>Date &amp; Time</th>
                <th>Pax</th>
                <th>Venue</th>
                <th>Coordinator</th>
                <th>Equipment Issues</th> <% } else { %>
                <th>Equipment ID</th>
                <th>Name</th>
                <th>Type</th>
                <th>Qty Damaged</th>
                <th>Qty Lost</th>
            <% } %>
        </tr>
    </thead>
    <tbody>
        <%
        List<Map<String, Object>> details = (List<Map<String, Object>>) reportData.get("details");
        if (details != null && !details.isEmpty()) {
            for (Map<String, Object> row : details) {
        %>
        <tr>
            <% if ("Event".equals(reportType)) { %>
                <td><strong><%=row.get("id")%></strong></td>
                <td><%=row.get("date")%><br><small><%=row.get("time")%></small></td>
                <td><%=row.get("pax")%></td>
                <td><%=row.get("venue")%></td>
                <td><%=row.get("coordinator")%></td>
                <td>
                    <% 
                        List<Map<String, Object>> issues = (List<Map<String, Object>>) row.get("issues");
                        if (issues != null && !issues.isEmpty()) {
                            for (Map<String, Object> issue : issues) {
                    %>
                        <div style="margin-bottom: 5px; padding: 5px; background: #fff5f5; border-radius: 4px; font-size: 12px;">
                            <strong><%=issue.get("eqpName")%></strong>:
                            <% if ((int)issue.get("qtyLost") > 0) { %>
                                <span style="color: red;">Lost (<%=issue.get("qtyLost")%>)</span>
                            <% } %>
                            <% if ((int)issue.get("qtyDamage") > 0) { %>
                                <span style="color: orange;">Damaged (<%=issue.get("qtyDamage")%>)</span>
                            <% } %>
                        </div>
                    <% 
                            }
                        } else { 
                    %>
                        <span>No Issues</span>
                    <% } %>
                </td>
            <% } else { %>
                <td><strong><%=row.get("id")%></strong></td>
                <td><%=row.get("name")%></td>
                <td><%=row.get("type")%></td>
                <td class="qty-danger"><%=row.get("damaged")%></td>
                <td class="qty-warning"><%=row.get("lost")%></td>
            <% } %>
        </tr>
        <% } } %>
    </tbody>
</table>


		<div class="no-print action-bar">
			<button class="cancel-btn" onclick="history.back()">Back</button>
			<button class="print-btn" onclick="window.print()">
				<i class="fas fa-print"></i> Download PDF
			</button>
		</div>
	</div>
</main>
</body>
</html>